name: settings_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fly_ui:
    git: https://github.com/niypoo/fly_ui.git
  app_configuration_service:
    git: https://github.com/niypoo/app_configuration_service.git
  bottom_sheet_helper:
    git: https://github.com/niypoo/bottom_sheet_helper.git
  launch_url_helper:
    git: https://github.com/niypoo/launch_url_helper.git
  firebase_authentication_service:
    git: https://github.com/niypoo/firebase_authentication_service.git
  authentication_view_module:
    git: https://github.com/niypoo/authentication_view_module.git
  localization_service:
    git: https://github.com/niypoo/localization_service.git
  theme_service:
    git: https://github.com/niypoo/theme_service.git
  user_firestore_helper:
    git: 
      url: git@github.com:niypoo/user_firestore_helper.git
  image_select_helper:
    git: https://github.com/niypoo/image_select_helper.git
  firebase_cloud_storage_service:
    git: https://github.com/niypoo/firebase_cloud_storage_service.git
  helpers:
     git: https://github.com/niypoo/helpers.git
  loading_service:
     git: https://github.com/niypoo/loading_service.git
  snackbar_helper:
     git: https://github.com/niypoo/snackbar_helper.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0